= Introdução

Este artigo técnico apresenta o desenvolvimento de um aplicativo desktop voltado ao acompanhamento de álbuns de figurinhas da Copa do Mundo FIFA 2026. O projeto parte de uma situação comum no contexto brasileiro: a coleção de figurinhas cresce rapidamente, as páginas passam a ter centenas de itens e a organização manual deixa de ser suficiente para acompanhar faltantes e repetidas.

O problema central do sistema é oferecer uma forma simples de responder três perguntas: quais figurinhas o usuário possui, quais ainda faltam e quais podem ser separadas para troca. Sem uma ferramenta de apoio, essas informações costumam ficar espalhadas em anotações, mensagens ou conferências manuais no próprio álbum, o que aumenta a chance de erro e dificulta a troca entre colecionadores.

Para isso, foi desenvolvida uma aplicação Java com interface Swing, banco de dados MySQL, acesso por JDBC e ambiente de banco provisionado com Docker. A escolha por Swing mantém o projeto dentro do escopo de uma aplicação desktop tradicional, enquanto o uso de JDBC deixa explícito o caminho entre as ações da interface e as operações SQL executadas no banco, conforme a documentação da plataforma Java @oracle_java_2026 e do MySQL Connector/J @oracle_mysql_connector_2026.

Os integrantes do grupo já tinham contato com outras linguagens, bibliotecas e frameworks antes do projeto. Mesmo assim, muitos recursos específicos do ecossistema Java não eram conhecidos no início. A experiência anterior ajudou principalmente a reconhecer padrões úteis e buscar equivalentes em Java: camada de dados, componentes visuais reutilizáveis, arquivos de configuração, separação por seções de tela e isolamento de infraestrutura. O desenvolvimento, portanto, não foi apenas uma implementação de requisitos, mas também uma tradução de conceitos já conhecidos para um ambiente novo.

A solução inclui uma tela inicial com resumo do progresso da coleção, uma tela de álbum com todas as seções e figurinhas, filtros por situação, busca por código ou nome, controle de quantidade e indicadores de repetidas. O escopo foi mantido propositalmente local e individual: a versão atual não possui login, sincronização entre computadores, múltiplos usuários ou negociação automática de trocas. Essas possibilidades são extensões naturais, mas não são necessárias para demonstrar as decisões de engenharia adotadas no projeto.
